(()=>{'use strict';const $=s=>document.querySelector(s);try{
 const T=THREE,canvas=$('#island'),renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.VSMShadowMap;
 const scene=new T.Scene();scene.background=new T.Color(0x94d5e8);scene.fog=new T.FogExp2(0x94d5e8,.0025);const camera=new T.PerspectiveCamera(43,1,.1,500);
 const hemi=new T.HemisphereLight(0xf2f9ff,0x779155,1.18);scene.add(hemi);const sun=new T.DirectionalLight(0xfff6e5,2.25);sun.position.set(-22,36,18);sun.target.position.set(0,0,0);sun.castShadow=true;sun.shadow.mapSize.set(matchMedia("(pointer:coarse)").matches?1024:2048,matchMedia("(pointer:coarse)").matches?1024:2048);Object.assign(sun.shadow.camera,{left:-29,right:29,top:29,bottom:-29,near:1,far:90});sun.shadow.radius=3;sun.shadow.blurSamples=8;sun.shadow.bias=-.00015;sun.shadow.normalBias=.075;scene.add(sun,sun.target);const fill=new T.DirectionalLight(0xd4eaff,.38);fill.position.set(20,14,-20);scene.add(fill);
 const island=SunIsland.create(scene),bridge=island.bridge,progi=BrokiPlush.create({detail:'light'});const polish=IslandPolish.enhance(island,scene);progi.name='Broki · rundere Kuschelfigur';const scale=.43;progi.scale.setScalar(scale);scene.add(progi);
 // Fuller plush geometry with the established green/yellow fabrics.
 progi.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});
 const player={x:island.spawn.x,z:island.spawn.z,y:island.groundAt(island.spawn.x,island.spawn.z),angle:Math.PI,walk:0,jump:0,velocity:0},keys=new Set(),pointers=new Map();let mode='overview',yaw=.40,pitch=.59,zoom=1,targetYaw=.40,targetPitch=.59,elapsed=0,last=0,walked=0,toastUntil=0,joyX=0,joyY=0,joyId=null,pinch=0,hasStarted=false,orbitOffset=0;
 const coins=IslandCoins.create(scene,island,(count,total)=>{$('#coin-count').textContent=count+' / '+total;notify(count===total?'Alle zehn Sonnenmünzen gefunden! ☀':'+1 Sonnenmünze');});
 const camTarget=new T.Vector3(0,1.9,0),desiredTarget=new T.Vector3(),desiredPosition=new T.Vector3(),look=new T.Vector3(),forward=new T.Vector2(),right=new T.Vector2();
 function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
 function notify(s){$('#toast').textContent=s;$('#toast').classList.add('show');toastUntil=elapsed+3.5;}
 function setMode(next,interacted=true){mode=next;if(interacted){hasStarted=true;$('#app').classList.add('playing');}$('#overview').classList.toggle('active',mode==='overview');$('#follow').classList.toggle('active',mode==='follow');$('#overview').setAttribute('aria-pressed',String(mode==='overview'));$('#follow').setAttribute('aria-pressed',String(mode==='follow'));if(mode==='overview'){targetYaw=.40;targetPitch=.59;zoom=1;}else{orbitOffset=0;targetYaw=player.angle+Math.PI;targetPitch=.53;zoom=1;}canvas.focus({preventScroll:true});}
 $('#overview').onclick=()=>setMode('overview');$('#follow').onclick=$('#explore').onclick=()=>setMode('follow');$('#touch-camera').onclick=()=>{if(mode!=='follow')setMode('follow');orbitOffset=0;targetYaw=player.angle+Math.PI;targetPitch=.53;};
 function home(){player.x=island.spawn.x;player.z=island.spawn.z;player.y=island.groundAt(player.x,player.z);player.angle=Math.PI;player.jump=0;player.velocity=0;joyX=joyY=0;keys.clear();notify('Zurück am Sonnensteg.');}$('#home').onclick=home;
 $('#photo').onclick=()=>{renderer.render(scene,camera);canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='Brokis-Sonneninsel.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Die echte 3D-Ansicht wurde gespeichert.');},'image/png');};
 function jump(){if(player.jump>.001||player.velocity>0)return;if(mode!=='follow')setMode('follow');player.velocity=5.8;}$('#jump').onclick=jump;
 const movementKeys=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];addEventListener('keydown',e=>{if(movementKeys.includes(e.code)){e.preventDefault();keys.add(e.code);if(!hasStarted||mode==='overview')setMode('follow');}if(e.code==='Space'){e.preventDefault();if(!e.repeat)jump();}if(e.code==='KeyR')home();if(e.code==='Escape')setMode('overview');});addEventListener('keyup',e=>keys.delete(e.code));
 function clearInput(){keys.clear();pointers.clear();joyX=joyY=0;joyId=null;$('#stick').style.transform='translate(0,0)';pinch=0;last=performance.now();}addEventListener('blur',clearInput);document.addEventListener('visibilitychange',clearInput);
 canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);}});
 canvas.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old)return;const dx=e.clientX-old.x,dy=e.clientY-old.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinch>0&&d>0)zoom=T.MathUtils.clamp(zoom*pinch/d,.65,1.55);pinch=d;}else{if(mode==='overview')targetYaw-=dx*.0045;else orbitOffset-=dx*.006;targetPitch=T.MathUtils.clamp(targetPitch+dy*.003,.28,1.15);}});
 const pointerUp=e=>{pointers.delete(e.pointerId);pinch=0;};canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('lostpointercapture',pointerUp);
 canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=T.MathUtils.clamp(zoom*Math.exp(e.deltaY*.001),.65,1.55);},{passive:false});
 const joystick=$('#joystick');function updateJoy(e){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.x-r.width/2,dy=e.clientY-r.y-r.height/2,d=Math.hypot(dx,dy),limit=34,f=d>limit?limit/d:1;joyX=dx*f/limit;joyY=dy*f/limit;$('#stick').style.transform=`translate(${dx*f}px,${dy*f}px)`;}
 joystick.addEventListener('pointerdown',e=>{e.preventDefault();joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);if(mode==='overview'||!hasStarted)setMode('follow');updateJoy(e);});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)updateJoy(e);});function releaseJoy(e){if(e.pointerId!==joyId)return;joyId=null;joyX=joyY=0;$('#stick').style.transform='translate(0,0)';}joystick.addEventListener('pointerup',releaseJoy);joystick.addEventListener('pointercancel',releaseJoy);joystick.addEventListener('lostpointercapture',releaseJoy);
 function move(dx,dz){const length=Math.hypot(dx,dz),steps=Math.max(1,Math.ceil(length/.06));dx/=steps;dz/=steps;let travelled=0;for(let i=0;i<steps;i++){const oldX=player.x,oldZ=player.z;const allowed=(x,z)=>island.canStand(x,z)&&island.groundAt(x,z)-island.groundAt(player.x,player.z)<.32;if(allowed(player.x+dx,player.z+dz)){player.x+=dx;player.z+=dz;}else{if(allowed(player.x+dx,player.z))player.x+=dx;if(allowed(player.x,player.z+dz))player.z+=dz;}travelled+=Math.hypot(player.x-oldX,player.z-oldZ);}return travelled;}
 function updatePlayer(dt){let turn=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joyX,drive=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-joyY;let moving=false;if((Math.abs(turn)>.12||Math.abs(drive)>.12)&&pointers.size===0)orbitOffset=0;
  if(Math.abs(turn)>.12)player.angle-=T.MathUtils.clamp(turn,-1,1)*dt*2.3;
  if(Math.abs(drive)>.12){const speed=T.MathUtils.clamp(drive,-1,1)*3.8,travel=move(Math.sin(player.angle)*speed*dt,Math.cos(player.angle)*speed*dt);moving=travel>.0001;walked+=travel;player.walk+=travel*7;}
  if(player.velocity!==0||player.jump>0){player.velocity-=14*dt;player.jump+=player.velocity*dt;if(player.jump<=0){player.jump=0;player.velocity=0;}}
  const y=island.groundAt(player.x,player.z);player.y=T.MathUtils.lerp(player.y,y,1-Math.exp(-dt*22));progi.position.set(player.x,player.y+player.jump+(moving?Math.abs(Math.sin(player.walk))*.045:0),player.z);progi.rotation.set(0,player.angle,moving?Math.sin(player.walk)*.022:0);progi.userData.arms.forEach((a,i)=>a.rotation.z=moving?Math.sin(player.walk)*.07*(i?1:-1):0);progi.userData.fur.forEach(o=>o.visible=mode==='follow');
  const loc=player.z>15?'Am Sonnensteg':Math.abs(player.x-bridge.x)<1.6&&Math.abs(player.z-bridge.z)<3?'Auf der Holzbrücke':player.z<-7&&player.y>2.8?'Auf dem Sonnenhügel':player.z<-2?'Auf der hinteren Wiese':'Auf der Blumenwiese';if($('#location').textContent!==loc)$('#location').textContent=loc;
 }
 function updateCamera(dt,instant=false){if(mode==='follow')targetYaw=player.angle+Math.PI+orbitOffset;const f=instant?1:1-Math.exp(-dt*5);yaw+=Math.atan2(Math.sin(targetYaw-yaw),Math.cos(targetYaw-yaw))*f;if(mode==='follow')yaw=targetYaw;pitch=T.MathUtils.lerp(pitch,targetPitch,f);let distance;if(mode==='overview'){desiredTarget.set(0,1.8,1.0);distance=46*zoom*Math.max(1,.96/camera.aspect);}else{desiredTarget.set(player.x,player.y+.85,player.z);distance=10.8*zoom*Math.max(1,.72/camera.aspect);}camTarget.lerp(desiredTarget,mode==='follow'?1:f);desiredPosition.set(camTarget.x+Math.sin(yaw)*Math.cos(pitch)*distance,camTarget.y+Math.sin(pitch)*distance,camTarget.z+Math.cos(yaw)*Math.cos(pitch)*distance);const terrainUnder=island.height(desiredPosition.x,desiredPosition.z);desiredPosition.y=Math.max(desiredPosition.y,terrainUnder+2.1);camera.position.lerp(desiredPosition,instant||mode==='follow'?1:1-Math.exp(-dt*7));look.copy(camTarget);camera.lookAt(look);}
 let frameCount=0;function frame(now){requestAnimationFrame(frame);if(document.hidden)return;const dt=Math.min(.05,(now-last)/1000||.016);last=now;elapsed+=dt;updatePlayer(dt);updateCamera(dt);island.update(elapsed);polish.update(elapsed);coins.update(elapsed,{x:player.x,z:player.z,y:player.y+player.jump});renderer.render(scene,camera);frameCount++;if(elapsed>toastUntil)$('#toast').classList.remove('show');}
 updatePlayer(.016);updateCamera(.016,true);renderer.render(scene,camera);$('#loading').hidden=true;requestAnimationFrame(frame);
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#error').hidden=false;});
 window.IslandStudy=Object.freeze({status:()=>({mode,player:{x:player.x,y:player.y,z:player.z,angle:player.angle,jump:player.jump,velocity:player.velocity},camera:{x:camera.position.x,z:camera.position.z,yaw},coins:coins.status(),walked,frames:frameCount,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,...island.stats}),canStandAt:(x,z)=>island.canStand(x,z),groundAt:(x,z)=>island.groundAt(x,z),bridge:{...island.bridge},dock:{...island.dock}});
}catch(error){$('#loading').hidden=true;$('#error').hidden=false;console.error(error);}})();
