(function(root){'use strict';root.IslandCoins={create(scene,island,onCollect){
 const T=THREE,coins=[],gold=new T.MeshStandardMaterial({color:0xffce35,metalness:.65,roughness:.27}),rim=new T.MeshStandardMaterial({color:0xffef9a,metalness:.5,roughness:.3});
 const disc=new T.CylinderGeometry(.24,.24,.065,24),ring=new T.TorusGeometry(.185,.018,6,24);
 const targets=[[-8,12],[8,11],[-13,6],[12,5],[-5,4],[-12,-5],[9,-5],[-5,-10],[6,-11],[0,-14]],locations=[];
 for(const [tx,tz]of targets){let best=null,score=Infinity;for(let dx=-2;dx<=2;dx+=.25)for(let dz=-2;dz<=2;dz+=.25){const x=tx+dx,z=tz+dz,d=dx*dx+dz*dz;if(d<score&&island.canStand(x,z,.45)&&island.pathDistance(x,z)>2&&island.inland(x,z)>3&&Math.abs(z-island.streamZ(x))>2.6){best=[x,z];score=d;}}if(!best)throw Error('No safe search coin near '+tx+','+tz);locations.push(best);}
 const sparks=180,positions=new Float32Array(sparks*3),colors=new Float32Array(sparks*3),geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(positions,3));geo.setAttribute('color',new T.BufferAttribute(colors,3));const material=new T.PointsMaterial({size:.22,vertexColors:true,transparent:true,opacity:0,depthWrite:false,blending:T.NormalBlending});const fireworks=new T.Points(geo,material);fireworks.frustumCulled=false;fireworks.visible=false;scene.add(fireworks);let celebrationStart=-1,celebrations=0,origin={x:0,y:0,z:0};
 const palette=[0xffbd19,0xff4787,0x29d8f4,0x93ed41];for(let i=0;i<sparks;i++){const c=new T.Color(palette[Math.floor(i/45)]);colors.set([c.r,c.g,c.b],i*3);}
 function celebrate(time,player){if(celebrationStart<0)return;const age=time-celebrationStart;if(age>4.5){fireworks.visible=false;return;}fireworks.visible=true;material.opacity=Math.min(1,(4.5-age)*.65);for(let i=0;i<sparks;i++){const burst=Math.floor(i/45),t=age-burst*.65,angle=i*2.39996,vertical=((i%45)/44)*2-1,speed=1.3+(i%7)*.15,rad=Math.sqrt(1-vertical*vertical),life=Math.max(0,t);positions[i*3]=origin.x+Math.sin(burst*2)*1.6+Math.cos(angle)*rad*speed*life;positions[i*3+1]=t<0?-100:origin.y+3+vertical*speed*life-.65*life*life;positions[i*3+2]=origin.z+Math.cos(burst*2)*1.6+Math.sin(angle)*rad*speed*life;}geo.attributes.position.needsUpdate=true;}

 for(const [x,z]of locations){if(!island.canStand(x,z,.1))throw new Error('Coin outside walkable ground: '+x+','+z);const group=new T.Group(),body=new T.Mesh(disc,gold);body.rotation.x=Math.PI/2;group.add(body);for(const side of[-1,1]){const edge=new T.Mesh(ring,rim);edge.position.z=side*.041;group.add(edge);}group.position.set(x,island.groundAt(x,z)+.65,z);group.name='Sonnenmünze '+(coins.length+1);scene.add(group);coins.push({group,x,z,base:group.position.y,collected:false});}
 let count=0;return{update(time,player){coins.forEach((c,i)=>{if(c.collected)return;c.group.rotation.y=time*1.6+i*.6;c.group.position.y=c.base+Math.sin(time*2.5+i)*.10;if(Math.hypot(player.x-c.x,player.z-c.z)<.68&&Math.abs(player.y+.55-c.group.position.y)<1.1){c.collected=true;c.group.visible=false;count++;onCollect(count,coins.length);if(count===coins.length){celebrationStart=time;celebrations++;origin={...player};}}});celebrate(time,player);},status:()=>({collected:count,total:coins.length,fireworksActive:fireworks.visible,celebrations,items:coins.map(c=>({x:c.x,z:c.z,collected:c.collected}))})};
}};})(window);
